package sg.edu.nus.cs2103.ui;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;

import sg.edu.nus.cs2103.sudo.logic.LogicHandler;
import sg.edu.nus.cs2103.sudo.logic.TaskManager;
import sg.edu.nus.cs2103.sudo.UIConstants;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

/**
 *
 * @author Liu Dake
 */





import javax.swing.text.DefaultCaret;

import org.jnativehook.GlobalScreen;
import org.jnativehook.NativeHookException;
import org.jnativehook.keyboard.NativeKeyEvent;
import org.jnativehook.keyboard.NativeKeyListener;


/**
 *
 * @author LiuDake
 */
public class MainFrame extends javax.swing.JFrame implements NativeKeyListener {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
		manager = TaskManager.getTaskManager();
		logicHandler = LogicHandler.getLogicHandler(manager, null);
		initComponents();
		toVisible();
    }
    
	public void nativeKeyTyped(NativeKeyEvent arg0) {
		// .TODO Auto-generated method stub
		// To implement unimplemented method
	}
	public void nativeKeyPressed(NativeKeyEvent e) {
		currentKey = e.getKeyCode();
		if (currentKey == UIConstants.KEYBOARD_TAB) {
			keyOne = true;
		}
		if (currentKey == UIConstants.KEYBOARD_SPACE) {
			keyTwo = true;
		}
		if (keyOne && keyTwo) {
			if (isShown) {
				isShown = false;
				toInvisible();
			} else {
				isShown = true;
				toVisible();
			}
		}
		if (e.getKeyCode() == NativeKeyEvent.VK_ESCAPE) {
			GlobalScreen.unregisterNativeHook();
			System.exit(0);
		}
	}

	public void nativeKeyReleased(NativeKeyEvent e) {
		currentKey = e.getKeyCode();
		if (currentKey == UIConstants.KEYBOARD_TAB) {
			keyOne = false;
		}
		if (currentKey == UIConstants.KEYBOARD_SPACE) {
			keyTwo = false;
		}
	}
	
	
	public void toInvisible() {
		this.setVisible(false);
	}

	public void toVisible() {
		this.setVisible(true);
	}
	
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	//to take over the output
    	outContent = new ByteArrayOutputStream();
		System.setOut(new PrintStream(outContent));
        jScrollPaneInput = new javax.swing.JScrollPane();
        jTextPaneInput = new javax.swing.JTextPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        MainTextPane = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        FloatingTextArea = new javax.swing.JTextArea();
		DefaultCaret caret = (DefaultCaret) FloatingTextArea.getCaret();
		caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextPaneInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextPaneInputKeyPressed(evt);
            }
        });
        
        jTextPaneInput.addKeyListener(new KeyAdapter() {
			public void keyPressed(KeyEvent e) {
				if (e.getKeyCode() == KeyEvent.VK_ENTER) {
					if ( jTextPaneInput.getText().equals("demo")) {
						if (isDemo) {
							MainTextPane.setFont(new java.awt.Font("Monaco",
									0, 17));
							FloatingTextArea.setFont(new java.awt.Font(
									"Monaco", 0, 12));
							 jTextPaneInput.setText(null);
							isDemo = false;
						} else {
							MainTextPane.setFont(new java.awt.Font("Monaco",
									0, 25));
							FloatingTextArea.setFont(new java.awt.Font(
									"Monaco", 0, 16));
							// mainTextFrame.setText("Font:Demo mode on");
							 jTextPaneInput.setText(null);
							isDemo = true;
						}
					} else {
						String userInput =  jTextPaneInput.getText();
						jTextPaneInput.setText(null);
						logicHandler.executeCommand(userInput);
						MainTextPane.setText(outContent.toString());
						outContent.reset();
						// String[] floatings =
						// updateFloating(manager.getFloatingTask());
						try {
							FloatingTextArea.setText(
									
									manager.displayFloatingTasks());
						} catch (IllegalStateException w) {
							FloatingTextArea
									.setText(UIConstants.MESSAGE_EMPTY_LIST);
						}
					}
				}
				
				//Add color change code here
				
				
				
			}
			
		});

        
        
        
        jScrollPaneInput.setViewportView(jTextPaneInput);

        MainTextPane.setEditable(false);
        MainTextPane.setForeground(new java.awt.Color(111, 222, 222));
        MainTextPane.setAutoscrolls(false);
        MainTextPane.setDragEnabled(false);
        MainTextPane.setFocusable(false);
        jScrollPane1.setViewportView(MainTextPane);

        FloatingTextArea.setEditable(false);
        FloatingTextArea.setColumns(20);
        FloatingTextArea.setRows(5);
        FloatingTextArea.setDragEnabled(false);
        FloatingTextArea.setFocusable(false);
        jScrollPane2.setViewportView(FloatingTextArea);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setFocusable(false);
        jScrollPane3.setViewportView(jTextArea1);
        
        if (manager.isReloaded()) {
			MainTextPane.setText(UIConstants.MESSAGE_WELCOME_TO_SUDO_RELOAD);
		} else {
			MainTextPane.setText(UIConstants.MESSAGE_WELCOME_TO_SUDO_FIRST);
		}
		try {
			FloatingTextArea.setText(manager.displayFloatingTasks());
		} catch (IllegalStateException e) {
			FloatingTextArea.setText(UIConstants.MESSAGE_EMPTY_LIST);
		}
		
	    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPaneInput)
            .add(layout.createSequentialGroup()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 340, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 250, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 250, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1)
                    .add(layout.createSequentialGroup()
                        .add(jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 579, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPaneInput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>                        

    private void jTextPaneInputKeyPressed(java.awt.event.KeyEvent evt) {                                          
    	
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
  
	private int currentKey;
	private Boolean keyOne = false;
	private Boolean keyTwo = false;
	private Boolean isShown = true;
	private Boolean isDemo = false;
	private ByteArrayOutputStream outContent;
	private TaskManager manager;
	private LogicHandler logicHandler;
    private javax.swing.JTextArea FloatingTextArea;
    private javax.swing.JTextPane MainTextPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPaneInput;
    private javax.swing.JTextPane jTextPaneInput;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration                   
}
