package sg.edu.nus.cs2103.sudo;

public enum COMMAND_TYPE {  
    ADD, DELETE, EDIT, FINISH, UNDO, REDO, SEARCH, FREE, SCHEDULE, SORT, 
    HELP, DISPLAY, INVALID, EXIT, INCOMPLETE, UNFINISH, ALL, PASS, DESTROY
}
